### ISSUE TITLE
TransformerMixin

### ISSUE THREAD

**Issue by eyadsibai** [yandex/rep#1]
It would be nice to have support for transformermixin too from sklearn and clustering too

**Comment by iamfullofspam** [comment]
Eyad, thanks for the question.
We have this in plans, but at this moment `REP` contains only sklearn's transformers.
In those situations transformer is needed (typically in the `pipeline`), sklearn transformers are used without any wrapper. 

Interface for transformers/clustering algorithms will be introduced together with support of other libraries (this is not in nearest plans, however).

**Comment by eyadsibai** [comment]
Thanks for your reply.
Excellent project I have to say.

Let me know if I could help in a way or another
