### ISSUE TITLE
FoldingRegressor

### ISSUE THREAD

**Issue by eyadsibai** [yandex/rep#17]
There is only a FoldingClassifier, it would be nice to have folding regressor too

**Comment by iamfullofspam** [comment]
Implemented FoldingRegressor and moved some logic to FoldingBase

https://github.com/yandex/rep/commit/9dd8eee7132ffa6fa77a373b8622824a699329bc
https://github.com/yandex/rep/commit/9959297556d04250433f71b6c9232ade935a5130
