### ISSUE TITLE
Use the new TMVA-related functions in root_numpy

### ISSUE THREAD

**Issue by ndawe** [yandex/rep#2]
This isn't really an issue but I just wanted to let you know that root_numpy now provides functions that can feed NumPy arrays directly to TMVA Factories or Readers:

http://rootpy.github.io/root_numpy/reference/index.html#module-root_numpy.tmva

So there is no longer any need to convert the arrays to TTrees in a temporary ROOT file.

**Comment by tata-antares** [comment]
https://github.com/yandex/rep/releases/tag/0.6.1
