### ISSUE TITLE
train_test_split in sklearn perserves columns now

### ISSUE THREAD

**Issue by amueller** [yandex/rep#23]
minor remark: in scikit-learn (since 0.16 I think) ``train_test_split`` should work as yours.
If you have any other api annoyances that you need to work around, let me know ;)

ps: awesome stuff!

**Comment by arogozhnikov** [comment]
Wow. Thanks for the remark, Andreas!
I checked that this indeed happened in 0.16.

I'll replace this with default scikit-learn function in next release.
