### ISSUE TITLE
can we have an option to support other ipython parallel engines by means of ipython-cluster-helper?

### ISSUE THREAD

**Issue by anaderi** [yandex/rep#26]
https://github.com/roryk/ipython-cluster-helper

**Comment by arogozhnikov** [comment]
We use only `map`. So if cluster is able to run map with custom function (which takes any objects), we'll be able to use it as well.

**Comment by anaderi** [comment]
https://github.com/roryk/ipython-cluster-helper
seems to be pretty unstable. close for now.
