### ISSUE TITLE
New REP docker version running in /var/lib/docker/volumes/ instead of ~/rep_container

### ISSUE THREAD

**Issue by lodurality** [yandex/rep#53]
Hi. 

I had old REP docker version in ~/rep_container which started with run.sh script on 8080 port. I updated REP and it broke: `sudo $REPDIR/run.sh` worked, but I couldn't connect to localhost:8080 (connection refused). I've decided to update docker and REP according to new instructions: https://github.com/yandex/rep/wiki/Install-REP-with-Docker-(Linux).

1. I installed Docker, according to instructions. 
2. `netstat -anl | grep 8888` gave empty result
3. `git checkout https://github.com/yandex/rep.git` didn't work (pathspec did not match any file(s) known to git), so I used `git clone` instead.
4. First run of `sudo make run` was successful and installed container.  
5. I rebooted and second `sudo make run` gave the following

*docker run -ti --rm -p 8888:8888 --name rep yandex/rep:0.6.4  
Error response from daemon: Conflict. The name "rep" is already in use by container 3af0884aeedb. You have to remove (or rename) that container to be able to reuse that name.
make: *** [run] Error 1*
6. I ran `sudo docker images`

*REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
yandex/rep          0.6.4               18a48bc5a3b6        8 hours ago         2.635 GB
anaderi/rep         latest              63c3db2850b6        4 months ago        1.649 GB
<none>              <none>              91c95931e552        7 months ago        910 B*
7. I tried `sudo docker start rep`. It worked and I opned REP on localhost:8888. But its working folder changed. Now it is /var/lib/docker/volumes/dbcc7ff99538007d9c6b244fb6b8f03bdcfd564f6076b36d79fa3330d2041107/_data/. It is quite unhandy, because it requires superuser rights to access and not conveniently located at all.

Question: Is it a new system or did I something wrong? If latter, how to I fix it and run REP container in handy folder?

**Comment by anaderi** [comment]
@lodurality , thanks for reporting. 
Indeed we’ve changed things a bit how REP runs within Docker. 
in particular:

- default port number is back to Jupyter default port number 8888 
- for most docker commands you have to use `make`

Also

- thanks for typo notice: «git checkout» -> «git clone» on Wiki
- between step 5 & 6 it was complaining about container with name ‘rep’, not image. so to clear previous one, just run `make remove`
- I’ve added option for `make` to specify `notebooks` folder - `-e NOTEBOOKS=path_my_notebooks_folder` (pick it from https://github.com/anaderi/rep/blob/master/Makefile)
e.g.:

        make -e NOTEBOOKS=~/notebooks run

PS you don’t have to use `sudo` (after adding yourself to `docker` group by `usermod -G docker $(whoami)`)

**Comment by lodurality** [comment]
It looks like `make` doesn't see/use this option. Here is what I did:

1. I removed all containers and images. 
2. Added myself to `docker` group.
3. Changed Makefile in rep directory for a new one.
4. Installed REP container again
5. Tried `make -e NOTEBOOKS=~/notebooks run`, but it still starts notebook in in /var/lib/docker/volumes/.../_data/.  
6. Also tried to run it with option NOTEBOOK_DIR instead of NOTEBOOKS, because I found the following code in output, but it didn't work either. 

```
	NOTEBOOK_DIR=/notebooks
	git clone $JPY_GITHUBURL $NOTEBOOK_DIR
	$HOME/miniconda/envs/jupyterhub_py3/bin/jupyterhub-singleuser \
	  --port=8888 \
	  --ip=0.0.0.0 \
	  --user=$JPY_USER \
	  --cookie-name=$JPY_COOKIE_NAME \
	  --base-url=$JPY_BASE_URL \
	  --hub-prefix=$JPY_HUB_PREFIX \
	  --hub-api-url=$JPY_HUB_API_URL \
	  --notebook-dir=$NOTEBOOK_DIR
	exit $?
```
