### ISSUE TITLE
Support for build on hosted on (ana)conda

### ISSUE THREAD

**Issue by e-gillies-ix** [yandex/rep#87]
I see that some of the continuous integration scripts support conda builds, although not all the dependencies are installed this way.  Is there any hope of seeing a build on conda soon for Linux x86_64 systems?

The reason I ask is that I have accounts on numerous batch systems, none of which I have root access or have any way to use docker.  They're all linux-based though, as is the norm.  So far as I know, this is the case for many researchers.

It'd be great to see a way to quickly install REP on these systems.  This would: 

- Cut down on the time needed to introduce people to REP
- Hook into the environment management and environment logging provided by conda
- Easily and quickly deploy REP on supercomputing nodes while requiring little of their filesystem

This is especially useful for ensuring the ROOT install is sane.  I know there has already been a lot of work in the direction of making REP easy to access and install.  Perhaps this could be a healthy addition?

**Comment by arogozhnikov** [comment]
Well, I don't think we have enough time to support and test conda builds, but you can use conda right now as it is done in integration scripts. 

This isn't much harder:
- download (wget) appropriate .yaml for environment
- e.g. `wget https://github.com/yandex/rep/blob/master/ci/environment-rep2.yaml` for python 2
- `conda env create -q --file environment-rep2.yaml`
- `conda activate rep_py2`
- `pip install rep`

This should work

**Comment by arogozhnikov** [comment]
@e-gillies-ix did you try the instructions above?

**Comment by e-gillies-ix** [comment]
Yeah, this recepie works fine.  I guess I was hoping to have it all in the .yaml file, i.e. excluding the last ```pip install rep command```, but this really isn't worth the extra effort...

Thanks!
Ewen

**Comment by anaderi** [comment]
@e-gillies-ix , you can add `rep` to `environment.yaml` like this:

```
dependencies:
  - pip:
    - rep
```

**Comment by e-gillies-ix** [comment]
ahh, okay, this is a bit cleaner then.  Thanks!
